package com.example.startupindonesia;

import java.util.ArrayList;

public class StartupsData {
    public static String[][] data = new String[][]{
            {"Alodokter", "Health", "Alodokter adalah perusahaan kesehatan digital nomor satu di Indonesia dengan lebih dari 18 juta pengguna aktif setiap bulannya. Kehadiran Alodokter di Indonesia sejak 2014 lalu telah mengubah poros layanan kesehatan Indonesia secara signifikan dalam penyediaan informasi medis yang mudah dipahami, akurat, dan dapat diakses oleh siapa saja. Semua informasi disusun oleh tim dokter dalam bahasa Indonesia.", "https://media.licdn.com/dms/image/C510BAQHFe65uQ7nB_Q/company-logo_200_200/0?e=2159024400&v=beta&t=EX-JHJvGOfp-l_twG6X0__UGoXDQmHOIlaBVtbDR3A0"},
            {"Blibli", "Marketplace", "Blibli.com adalah salah satu situs web perdagangan elektronik di Indonesia. Blibli adalah produk pertama PT Global Digital Niaga yang merupakan anak perusahaan Djarum di bidang digital yang didirikan pada tahun 2010. Blibli bekerja sama dengan penyedia jasa teknologi, mitra logistik, perbankan serta mitra dagang dengan standar tertentu untuk menciptakan sistem back-end yang bisa memenuhi kebutuhan pengguna blibli. Kantor pusat Blibli bermarkas di Jakarta Barat dengan biaya infrastruktur seperti server dan jaringan hampir mencapai Rp 100 miliar.", "https://files.startupranking.com/startup/thumb/9440_e45a3cdde6ed4031e4884e5a9eec7d4b7d770b24_blibli_m.jpg"},
            {"Bukalapak", "Marketplace", "Bukalapak merupakan salah satu pusat perbelanjaan daring (online marketplace) di Indonesia (biasa dikenal juga dengan jaringan toko daring ) yang dimiliki dan dijalankan oleh PT. Bukalapak. Bukalapak didirikan pada 10 Januari 2010 oleh Achmad Zaky, Nugroho Herucahyono, dan Fajrin Rasyid di sebuah rumah kos di Bandung, Jawa Barat. Bukalapak telah menjadi 1 dari 4 unicorn asal Indonesia pada tahun 2017. Bukalapak secara konsisten berupaya memperluas literasi digital dan membangun usaha kecil dan menengah (UKM) di Indonesia.", "https://files.startupranking.com/startup/thumb/9559_a86e084c0311c6f064df7c23bc21c4dc495e0068_bukalapak_m.png"},
            {"Codepolitan", "Media", "CodePolitan adalah media edukasi dan informasi tentang pemrograman dan teknologi. CodePolitan dibangun untuk memfasilitasi para developer dalam mendapatkan informasi dan pengetahuan seputar pemrograman dan teknologi. Konten-konten yang ada di CodePolitan disusun sedemikian rupa dan dalam bahasa Indonesia agar mudah dipahami oleh para developer Indonesia.", "https://admin.rumahkomunitas.com/uploads/komunitas/lg_091218082347_24471_74eecacf22614aefb17dfd382b55f7744cdb3e2e_codepolitan_m.png"},
            {"Dicoding", "Education", "Dicoding adalah sebuah perusahaan startup yang bertujuan mengembangkan ekosistem developer di Indonesia. Berdiri sejak 5 Januari 2015, Dicoding memiliki platform pembelajaran elektronik di laman Dicoding.com. Dicoding telah terakreditasi sebagai satu-satunya Google Developers Authorized Training Partner di Indonesia dan menjadi mitra Badan Ekonomi Kreatif(BEKRAF) dalam menyelenggarakan program pembangunan ekonomi kreatif digital seperti Bekraf Developer Day.", "https://blog.dicoding.com/wp-content/uploads/2017/10/dicoding-logo-square.png"},
            {"Finansialku", "Money Management", "Finansialku adalah satu-satunya perusahaan perencana keuangan yang telah memiliki portal edukasi dan aplikasi perencanaan keuangan. Kami sudah banyak bantu klien untuk pengelolaan keuangan (cashflow) dan perencanaan keuangan (financial planning).", "https://files.startupranking.com/startup/thumb/540648_02253a2fce5fc5fba2fab52bccd592a4ee448b4e_finansialku-com_m.png"},
            {"Gamebrott", "Videogames", "Gamebrott adalah Portal berita game yang berfokus pada perkembangan video game dengan rubrik - rubrik informatif agar pengetahuan gamer Indonesia gak kurang update", "https://files.startupranking.com/startup/thumb/23753_6dd7d234451c81f5f447d9e8903c7c0d5c76036e_gamebrott_m.png"},
            {"Go-Jek", "Transportation", "GO-JEK adalah merupakan perusahaan berjiwa sosial yang memimpin revolusi industri transportasi Ojek. GO-JEK bekerjasama  dengan para pengendara Ojek berpengalaman di Jakarta, Bandung, Bali & Surabaya dan menjadi solusi utama dalam pengiriman barang, pesan antar makanan, berbelanja dan berpergian di tengah kemacetan. GoJek Indonesia berdiri pada tahun 2011 sebagai social enterpreneurship inovatif untuk mendorong perubahan sektor transportasi informal agar dapat beroperasi secara profesional. Manajemen GoJek menerapkan sistem bagi hasil dengan sekitar 1000 pengemudi ojek yang saat ini berada di bawah naungan GoJek dan tersebar di Jabodetabek. Pembagiannya adalah, 80% penghasilan untuk pengemudi ojek dan 20%-nya untuk GoJek.", "https://files.startupranking.com/startup/thumb/29638_cd1d8c3f489fb535304efd20825d02a329a8a94c_go-jek_m.jpg"},
            {"Mamikos", "Rental", "MAMIKOS adalah aplikasi pencari kost no.1 di Indonesia. MAMIKOS menyediakan layanan pencarian kamar kost yang gampang dan cepat serta memiliki data kost yang akurat. MAMIKOS menyajikan data kamar kost dengan detail fasilitas kost yang lengkap mulai dari fasilitas kamar kost, kamar mandi, fasilitas umum kost, dilengkapi dengan foto-foto kost untuk setiap detail kost, dan semua data kost yang ada di MAMIKOS sudah diverifikasi oleh agen MAMIKOS. Setiap Kamar Kost yang ada di MAMIKOS benar-benar kami datangi, kami verifikasi, dan kami seleksi datanya. Selain itu informasi ketersediaan kamar kost dan harga kost kami update setiap 1-2 minggu sekali untuk memberikan informasi terupdate kepada calon penghuni kost. Setiap kamar kost yang ditambahkan oleh agen kami, atau ditambahkan oleh pemilik atau pengguna akan kami verifikasi dan kami hubungi kembali untuk meminta ijin penayangan dan memberitahukan bahwa kamar kost tersebut telah siap diiklankan secara gratis.", "https://files.startupranking.com/startup/thumb/29686_071747c4830620a5074c4cc6ad5730e84c3d174f_mamikos_m.png"},
            {"RuangGuru", "Education", "Ruangguru merupakan perusahaan teknologi terbesar dan terlengkap di Indonesia yang berfokus pada layanan berbasis pendidikan dan telah memiliki lebih dari 6 juta pengguna serta telah mengelola lebih dari 150.000 guru yang menawarkan jasa di lebih dari 100 bidang pelajaran. Perusahaan ini didirikan sejak tahun 2014 oleh Belva Devara dan Iman Usman, yang keduanya berhasil masuk dalam jajaran pengusaha sukses dibawah 30 tahun melalui Forbes 30 under 30 untuk teknologi konsumen di Asia.", "https://files.startupranking.com/startup/thumb/15046_40c76ccfc3f2ad3332796553bdf513d51b1e68d8_ruangguru_m.png"},
            {"RumahWeb", "Hosting", "Rumahweb adalah salah satu dari pemimpin pasar hosting di Indonesia dengan lebih dari 23000 pelanggan dan terus berkembang.", "https://files.startupranking.com/startup/thumb/30211_c33bca2fdcaf6c7c4930b1de9381667dc9d4452e_rumahweb-indonesia_m.jpeg"},
            {"Traveloka", "Travelling", "Traveloka adalah perusahaan teknologi terkemuka di Indonesia yang menyediakan layanan pencarian dan pemesanan tiket pesawat dan hotel secara online.", "https://files.startupranking.com/startup/thumb/9779_706891cbd766d67920e3a4df089b2516646a7dbe_traveloka_m.png"},
            {"Zenius Education", "Education", "Zenius Education adalah adalah sebuah website belajar online yang kami sediakan bagi siswa-siswi mulai kelas 1 SD - 12 SMA/SMA/MA di seluruh Indonesia untuk belajar memahami materi sekolah, latihan soal, serta mengevaluasi pembahasan soal untuk 11 mata pelajaran yang sesuai dengan kurikulum KTSP, Kurikulum 2013, dan Kurikulum 2013 Revisi. Website zenius.net juga dilengkapi dengan persiapan Ujian Nasional (USBN + UNBK), SBMPTN, dan Ujian Mandiri masuk Perguruan Tinggi.", "https://files.startupranking.com/startup/thumb/15353_245ac7d0bd49a283872a56b0d409a0612cdda221_zenius-education_m.png"},

    };

    public static ArrayList<Startup> getListData(){
        ArrayList<Startup> list = new ArrayList<>();
        for(String[] aData : data){
            Startup startup = new Startup();
            startup.setName(aData[0]);
            startup.setCategory(aData[1]);
            startup.setDescription(aData[2]);
            startup.setPhoto(aData[3]);

            list.add(startup);
        }
        return list;
    }
}
